---
# Create ec2 instance and add it to ansible inventory
- name: Create a sandbox instance
  hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - amazon.aws
  vars:
    keyname: todokey
    instance_type: t2.micro
    security_group: sg-09676125f9ce3765e
    image: ami-0faab6bdbac9486fb
    region: eu-central-1
    tag_name: TestServer
    ansible_python_interpreter: "/opt/venv/bin/python3.11"

  tasks:
    - name: Launch instance
      amazon.aws.ec2_instance: # Achten Sie auf die korrekte Einrückung hier
        key_name: "{{ keyname }}"
        security_groups: 
          - "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: subnet-05774febd9cfbd51a
        network:
          assign_public_ip: yes
        tags: 
          Name: "{{ tag_name }}"
      register: ec2

    - name: Debug EC2 instance creation result
      debug:
        var: ec2

    - name: Add new instance to hosts group for test
      lineinfile:
        path: "~/ansible_hosts"
        regexp: "{{ item.network_interfaces[0].association.public_ip }}"
        insertafter: "[tstlaunched]"
        line: "{{ item.network_interfaces[0].association.public_ip }}"
        state: present
      loop: "{{ ec2.instances }}"
      loop_control:
        label: "{{ item.instance_id }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.network_interfaces[0].association.public_ip }}"
        port: 22
        state: started
      loop: "{{ ec2.instances }}"
      loop_control:
        label: "{{ item.instance_id }}"
